Disable Python 3.14
- Disable until #581 is fixed.
- Add job to meet the required statuses without needing to reconfigure the status checks.

diff --git a/.github/workflows/self_test.yml b/.github/workflows/self_test.yml
--- a/.github/workflows/self_test.yml
+++ b/.github/workflows/self_test.yml
@@ -14,7 +14,8 @@ jobs:
           - '3.11'
           - '3.12'
           - '3.13'
-          - '3.14'
+          # Enable once https://github.com/w3c/trace-context/issues/581 is fixed
+          # - '3.14'
 
     name: Run the python tests
     steps:
@@ -27,3 +28,20 @@ jobs:
       - run: pip install aiohttp
       - run: cd test && python self_test.py
         shell: bash
+
+  self-test:
+    name: Run the python tests
+    needs: [ build ]
+    if: ${{ !cancelled() }}
+    env:
+      TESTS_SUCCESS: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
+    runs-on: ubuntu-latest
+    steps:
+    - run: |
+        if [ "$TESTS_SUCCESS" == "true" ]
+        then
+          echo 'Self tests successful ✅'
+        else
+          echo 'Self tests failed ❌'
+          exit 1
+        fi
